import type { Metadata } from "next";
import { alata, manrope } from "./fonts";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${alata.variable} ${manrope.variable} antialiased min-h-dvh flex flex-col`}
      >
        <Nav />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
