import type { Metadata } from "next";
import { alata, manrope } from "./fonts";
import "./globals.css";
import Nav from "../components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.variable} ${manrope.variable} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
